---
- hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Perform an upgrade.
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes

    - name: Upgrade Linux Image.
      ansible.builtin.apt:
        name: linux-image-amd64

    - name: Reboot the server (if required).
      ansible.builtin.reboot:

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
